[package]
name = "folio"
version = "0.1.0"
description = "Beautiful print preview for Markdown"
authors = ["Junaid Anjum <junaidanjum@live.com>"]
edition = "2021"
license = "MIT"

[lib]
name = "folio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
notify = "8"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
